# Generated by Django 3.2.3 on 2021-05-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_alter_song_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
